name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm ci
      - run: npm run build
        env:
          VITE_BASE_URL: /my-fullstack-app/
          VITE_API_URL: https://chat-app-backend-fdhs.onrender.com
      - run: |
          cd dist
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Deploy to gh-pages - $(date -u)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-pages --force
        working-directory: ./frontend
